name: 'release'

on:
    release:
        types: [published]

jobs:
    push_to_registry:
        name: Push Docker image to GitHub Packages tagged with "latest" and version number.
        runs-on: ubuntu-latest
        permissions: 
            contents: read
            packages: write
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v3
              with:
                ref: ${{ github.event.release.target_commitish }}
                # list of Docker images to use as base name for tags
                images: |
                  ghcr.io/NCATSTranslator/workflow-runner
                # add latest tag when appropriate
                flavor: |
                  latest=auto
                # generate Docker tags based on the following events/attributes
                tags: |
                  type=semver,pattern={{version}}
                  type=semver,pattern={{major}}.{{minor}}
                  type=semver,pattern={{major}}
                  type=sha

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to GHCR
              uses: docker/login-action@v1
              with:
                registry: ghcr.io
                username: ${{ github.repository_owner }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                context: .
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
